version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEO_AVAL_API_KEY=${GEO_AVAL_API_KEY}
      - RELOAD=true
    env_file:
      - .env.dev
    volumes:
      - ./api:/app
    networks:
      - geo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules  
      - /app/.next         

    networks:
      - geo-network
    restart: unless-stopped

networks:
  geo-network:
    driver: bridge