version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEO_AVAL_API_KEY=${GEO_AVAL_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - geo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./geo_interface
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - geo-network
    restart: unless-stopped

networks:
  geo-network:
    driver: bridge